Added intent from WelcomeActivity to RegisterActivity
Elevate-Lab/college-notification-app pull request #39
Opened 2020-11-01 15:17 UTC by cyber-venom003

# Pull Request 

## Proposed Changes
- Added an intent from WelcomeActivity to RegisterActivity using onClickListener

2020-11-01 16:49 UTC, Pranshu-Tripathi requested changes
@cyber-venom003 the coding part is correct but some unwanted files have changed in the PR.
.giignore and render.experimental.xml etc are changed. Please make a PR with changes only in welcomeActivity.java

2020-11-01 16:52 UTC, cyber-venom003 commented
@Pranshu-Tripathi they aren't changed by me, they are changed automatically by Android Studio. I don't think it would create any mess. 👀 🙄

2020-11-02 11:18 UTC, siddhantdrk approved these changes

2020-11-02 11:19 UTC, Pranshu-Tripathi approved these changes

2020-11-02 11:22 UTC, Pranshu-Tripathi approved these changes

2020-11-02 11:24 UTC, merged